version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: "aws-waraclecoding"
          ContainerPort: "8282"
        PlatformVersion: "LATEST"